# Up and Running with Python3
# NumPy

NumPy is a fundamental package for scientific computing with Python. 
Is a Python library adding support for multi-dimensional arrays and matrices, as well as many useful mathematical functions to operate on these arrays.

<img src="data/logos/775px-NumPy_logo.svg.png" style="width: 200px;">

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.17.2


In the previous notebook, we saw how to construct lists. Now, we will start from lists, and see how we can construct numpy arrays from them.

In [3]:
masses_list = [0.511, 105.66, 1.78e3]
masses_array = np.array(masses_list)
masses_array

array([5.1100e-01, 1.0566e+02, 1.7800e+03])

Multiply every element by a number:

In [4]:
masses_array_gev = masses_array * 1e-3
masses_array_gev

array([5.1100e-04, 1.0566e-01, 1.7800e+00])

To get the size of the array, you can use the `len()` function, or the `.size` attribute.

You can get the shape of the object by using the `.shape` attribute

In [5]:
# EXCERCISE: Check that len and size give the same result. What does shape return?
print('len is ', len(masses_array))
print('size is ', masses_array.size)
print('shape is ', masses_array.shape)

len is  3
size is  3
shape is  (3,)


In [6]:
# EXCERCISE: Try np.linspace, np.zeros, np.ones
np.linspace(5, 15, 9)
np.zeros(9)
np.ones(9)
np.zeros((5, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## NumPy DataTypes

Up until this point, we have been using the default datatypes that NumPy selects for arrays. In the cases for arange and linspace, the default types are integers. 

In the case of zeros and ones, the default type is floating point. Each of these functions has a `dtype` parameter. For example, we can look here and we see linspace has a `dtype` parameter and its default value is set to `None`. You can use this parameter to determine the datatype for each element in an array. Remember that each element must have the same datatype. 

At this [link](https://docs.scipy.org/doc/numpy/user/basics.types.html) you can find all the NumPy datatypes.

In the previous examples, we saw that the `ones` function and the `zeros` function return arrays that contain floating point values. 

You can change this and select the datatype that you want by setting a value for the `dtype` parameter. 
For example you can do `np.ones(9, dtype='int64')`.

In [7]:
# EXCERCISE: Create an array with zeros that has 11 elements, each of which is a 64-bit integer
a = np.zeros(11, dtype='int64')
print(a, type(a))
a.dtype

[0 0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>


dtype('int64')

And...there is also the _complex_ data type!

You can specify a complex type in python using `j` as imaginary number, as in `1+2j`.

In [8]:
# EXCERCISE: Try to add an imaginary number to a numpy array and print the array
masses_list = [0.511, 105.66, 1.78e3]
masses_list.append(1+2j)
masses_array = np.array(masses_list)
masses_array

array([5.1100e-01+0.j, 1.0566e+02+0.j, 1.7800e+03+0.j, 1.0000e+00+2.j])

## Array Indexing and Slicing

In [9]:
masses_array = np.array([2.2, 4.7, 0.511, 1.28, 96, 105.66, 173e3, 4.18e3, 1.78e3, 0, 0, 91.19e3, 80.39e3, 124.97e3])

You can use negatixe index to start counting from the end of the array. 

For example, to select the last element:

In [10]:
masses_array[-1]

124970.0

Or to select the penultimate element:

In [11]:
masses_array[-2]

80390.0

And so on...

### Slicing

A basic slice syntax is `i:j:k` where `i` is the starting index, `j` is the stopping index, and `k` is the step:

In [12]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
x[1:7:2]

array([1, 3, 5])

Now, if `i` is not given, it defaults to 0.

If `j` is not given, it defaults to the lenght of the array (call it `n`).

If `k` is not given it defaults to 1.


**Example** `i = 3`, `j` and `k` defaulted to `n` and 1:

In [13]:
x[3:]

array([3, 4, 5, 6, 7, 8, 9])

**Example** `i` defaulted to 0, `j = 4` and `k` defaulted and 1:

In [14]:
x[:4]

array([0, 1, 2, 3])

**Example** `i` defaulted to 0, `j = 4` and `k = 2`:

In [15]:
x[:4:2]

array([0, 2])

## Linear Algebra

The `np.matrix` function returned a matrix from an array like object, or from a string of data. 

A matrix is a specialized 2D array that retains its 2D nature through operations. 

It has special operators such as asterisk for matrix multiplication, and a double asterisk for matrix power or matrix exponentiation operations.

Let's contruct the a CKM matrix:

In [16]:
ckm_matrix = np.matrix([[0.97427, 0.22534, 0.00351 ],
                        [0.22520, 0.97344, 0.0412  ],
                        [0.00867, 0.0404,  0.999146]])

In [17]:
ckm_matrix

matrix([[0.97427 , 0.22534 , 0.00351 ],
        [0.2252  , 0.97344 , 0.0412  ],
        [0.00867 , 0.0404  , 0.999146]])

In [18]:
type(ckm_matrix)

numpy.matrix

Again, we can use the `.shape` attribute to see what is the shape of this matrix:

In [19]:
ckm_matrix.shape

(3, 3)

And also `ndim` to see the number of dimensions:

In [20]:
ckm_matrix.ndim

2

Let's use the `help` function to see what opetations are available:

In [21]:
# help(np.matrix)

Let's the transpose attribute `.T` to calculate the transpose of this matrix. 

Next we'll use another attribute, `.I`, to calculate the inverse of this matrix. Notice that the inverse is calculated on my first matrix, and not upon the transform of my first matrix. 

For example, is the transpose of the CKM matrix:

In [22]:
ckm_matrix.T

matrix([[0.97427 , 0.2252  , 0.00867 ],
        [0.22534 , 0.97344 , 0.0404  ],
        [0.00351 , 0.0412  , 0.999146]])

In [23]:
# EXCERCISE: Check that the CKM matrix is unitary:
result = ckm_matrix * ckm_matrix.I.T
result[result < 1e-2] = 0
result

matrix([[0.999931  , 0.        , 0.        ],
        [0.        , 0.99999997, 0.        ],
        [0.        , 0.        , 1.00003722]])

## NumPy Example: MicroBooNE Cross Section Mearurement
## $\chi^2$ Calculation

Let's start by getting the MicroBooNE extracted data cross section, as well as the predictions according to GENIE, GiBUU and NuWro, and the covariance matrix. This data is saved into txt files in the `data/` directory.

The cross section is a double differential cross section calculated over 42 bins in muon mometum and angle.

From [PRL 123 131801](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.123.131801).

In [24]:
xsec_data    = np.loadtxt('data/ub_xsec_data.txt')
xsec_geniev2 = np.loadtxt('data/ub_xsec_geniev2.txt')
xsec_geniev3 = np.loadtxt('data/ub_xsec_geniev3.txt')
xsec_gibuu   = np.loadtxt('data/ub_xsec_gibuu.txt')
xsec_nuwro   = np.loadtxt('data/ub_xsec_nuwro.txt')
cov_m        = np.loadtxt('data/microboone_cc_inclusive_covariance_matrix.txt')

# The matrix is importes as an ndarray, let's convert it to a matrix
cov_m = np.asmatrix(cov_m)

In [25]:
print('Covariance matrix:', cov_m, sep='\n')

Covariance matrix:
[[0.0014221  0.0024292  0.0020302  ... 0.0045393  0.0024758  0.00034129]
 [0.0024292  0.023726   0.017872   ... 0.023916   0.013979   0.0022713 ]
 [0.0020302  0.017872   0.01754    ... 0.017726   0.010885   0.0022958 ]
 ...
 [0.0045393  0.023916   0.017726   ... 0.10804    0.077947   0.010734  ]
 [0.0024758  0.013979   0.010885   ... 0.077947   0.071678   0.010127  ]
 [0.00034129 0.0022713  0.0022958  ... 0.010734   0.010127   0.00199   ]]


In [26]:
print('Data-extracted cross section:', xsec_data, sep='\n')

Data-extracted cross section:
[ 3.84353668e-02  2.53289692e-01  2.20457527e-01  4.17274526e-02
 -9.47941677e-04  1.38306972e-02  2.26293309e-01  2.89972283e-01
  5.85665149e-02 -2.31150586e-04 -3.09318252e-02  4.70738332e-01
  6.73681772e-01  1.34373251e-01 -1.09858630e-02  2.07742718e-01
  7.81307488e-01  3.51045752e-01 -1.32467184e-02  2.39985567e-01
  1.01731891e+00  6.40282893e-01  1.83263577e-02  2.50330031e-01
  1.25424953e+00  1.12325786e+00  7.37387074e-02  1.81042697e-01
  9.26557958e-01  1.52679070e+00  6.87849583e-01  3.37693050e-02
  2.30655790e-01  9.60081005e-01  1.80108964e+00  1.17512054e+00
  9.70709979e-02  1.78672667e-01  9.77337456e-01  1.69361706e+00
  1.38792495e+00  1.94159564e-01]


Let's calculate the $\chi^2$ between data $x_i$ and prediction $\mu_i$ in bin $i$, and given the covariance matrix $E$: 

$\chi^2 = \sum_{ij} (x_i - \mu_i) \cdot E^{-1}_{ij} \cdot (x_j - \mu_j)$

In [27]:
# EXCERCISE: Calculate the chi2 between data and prediction:

# Difference between x_j and mu_j, elementwise:
delta = xsec_data - xsec_geniev2

# Inverse of the covariance matrix:
cov_m_inv = cov_m.I

# Matrix multiplication between E and delta
t = cov_m_inv.dot(delta)

# Final multiplication
chi2 = delta.dot(t.T)

print('chi2 = ', chi2)

chi2 =  [[245.90854256]]


In [28]:
def chi2(data, prediction, cov_m):
    delta = data - prediction
    cov_m_inv = cov_m.I
    t = cov_m_inv.dot(delta)
    return delta.dot(t.T).item(0)

In [29]:
chi2(xsec_data, xsec_geniev2, cov_m)

245.90854256185807

In [30]:
print('GENIEv2 chi2 =', chi2(xsec_data, xsec_geniev2, cov_m))
print('GENIEv3 chi2 =', chi2(xsec_data, xsec_geniev3, cov_m))
print('GiBUU   chi2 =', chi2(xsec_data, xsec_gibuu,   cov_m))
print('NuWro   chi2 =', chi2(xsec_data, xsec_nuwro,   cov_m))

GENIEv2 chi2 = 245.90854256185807
GENIEv3 chi2 = 108.75939875546912
GiBUU   chi2 = 172.91813735442392
NuWro   chi2 = 126.43129852215583


In [31]:
# p-value
from scipy import stats
1 - stats.chi2.cdf(108, 42)

1.009037037258409e-07

# Conclusions
You know, you can also fly with Python. Let's try:

In [32]:
import antigravity

# Extras

### Reshape

The above array `masses_array` is a 1-D array with 14 elements in it. 

Numpy allows to resphape it easily. For example, we can transform it into a 2-D array with 7 columns and 2 rows.

There a few ways to do this. 

We can either change the `.shape` attribute directly, but is usually better to use the `np.shape()` function, which returns a new, reshaped, array:

In [33]:
masses_array_2d = np.reshape(masses_array, (7, 2))
masses_array_2d

array([[2.2000e+00, 4.7000e+00],
       [5.1100e-01, 1.2800e+00],
       [9.6000e+01, 1.0566e+02],
       [1.7300e+05, 4.1800e+03],
       [1.7800e+03, 0.0000e+00],
       [0.0000e+00, 9.1190e+04],
       [8.0390e+04, 1.2497e+05]])

## Statistics

In [34]:
import scipy as sp
from scipy.stats import norm

Generated normally distributed values

In [35]:
random_data_set = sp.randn(10000)
type(random_data_set)

numpy.ndarray

In [36]:
random_data_set.mean()

-0.005874525475690234

In [37]:
random_data_set.std()

1.0060965472758587

In [38]:
random_data_set

array([ 1.02105228,  1.28686257, -0.3400309 , ..., -0.59083932,
       -0.39471744, -0.44720252])

## Boolean Masks
Let's start with a numpy array

In [39]:
vector = np.array([26, 14, 1, -28, 8, 7])

Then, we create a "mask". We construct a list with contains True and False values, depending if the elements of `vector` are divisbile or not by 7.

In [40]:
mask = 0 == (vector % 7)

In [41]:
mask

array([False,  True, False,  True, False,  True])

Finally, we can applt this mask to our vector in order to select only elements that are divisible by 7:

In [42]:
vector[mask]

array([ 14, -28,   7])